---
- hosts: kubernetes
  user: root

  tasks:
    - name: deploy app on kubernetes
      command: kubectl apply -f app-deployment-manifest.yml

    - name: create service for app
      command: kubectl apply -f app-service-manifest.yml

    - name: update deployment incase image is updated in Dockerhub
      command: kubectl rollout restart deployment.apps/dhrvanesch-app
